gsheet_id = "1uObYRwdG-JfMf_Xh-wXJac1pHUpET6LM8R-i3sDIzoY"
drive_folder_id = "153WDIugS6XQjBm472csWr8mqet6_BRtd"

[gcp_service_account]
type = "service_account"
project_id = "kost-management-466414"
private_key_id = "fc8fed799f9328dc74ed40266e2f7873370390c9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCuBO/hZcksHyG1
XyOtbm3zLsiB7PEzGaE6/IzkrH/Svjd1V153B3ZbF82a4/CJguEE7wQyZe5UOvr7
IqukybbV23jLxl/QTYTPUqh05WS5WOXOAA5XQjuf0XFck2prn/i/q902qIVVwcVR
WhP3oOeYg2maSFTQtpGAL1JWVdChO1/xJFkQBXzq8kS63N7CZJUPKPm0dhN3MHNY
IsBU7g3x5dSoOfxl/0xSuemoYt6wCYXho8kzUr64jCbXgmrWXOERJLMdatC6KNia
heQd19csHzkD7fYcxIZ20CmioyqCSFWMi7UH6O/zRp9bcLG4qTehSmIRAu3TASgR
gGCEjdURAgMBAAECggEAJerdefd7xiliZuq8E2YkfwCKoATI6aGECB5PdORBVeIs
o1zOMJFnsKGXI1DXcJ8b+L874t9i9ueDGIWNcPKi7CZOQ9iNuA2sCqCwJAh30gsU
x7Yracf8xe4VDV7xqVHKGbmREf/WTcFTBU7jWumsjQbVU9C+6ltdiNjG0BkSxI6W
0pNBQmGXOlyBBfgSqZ3PtYtbFRxfjioHZi0WE0v6pm17uXKki6irT2y8qQnchzm5
nl9ZLb6WhbMVWKU6sZ4NeJjlGO2uo5Lu3GJnY5IM7TMI3UYKpQ7RV5sxNurVROAO
w5+rvnpLME1yHbzZjTAhSazWhbmo7Y34Gec5YCRIIQKBgQDtcytYsWLwaf1LnU1p
+FG3+iXnrTBvm/drXDv/bZeyYXGhtWdVHMgsMZe5PjIz56ROovy8SFxIg00nHXGj
p8gLsB4fRHuDebxwzW+MpFoMuMvObMzV/wSPPD+U63hCLv8EgSpv4Mon3dHUCVG9
0+9IV+p6Tdw2UjSs31XN7koaPwKBgQC7nTNNtskZaYNTbJBOLgbvqoqWrlzu9igm
0KcAAByY51zIjVAJRT/kd1OYSfKca+woCm5onRdfCnqbH9h/oyqT3ImPFPoQ2bVc
e784PvOHDsp8zIARuAptk4uwpOGL04yoUdNxElwiY+TnOufkp5mxcP3N5rcpiLTc
AUXoEzkcrwKBgQCQl6U5qSs6gxA/T1aoxRHeGnGilo/8JtmPgub2L+JEOZpcgn6e
EZzDbJ+bqgggG1qumAmXDelELtB4lTFyGuVyWJi/KZCdCzB48GCRIDPFs3JIDXDe
jyBTqLh/ErR0ePHJ6G3TGut/Q1BW8iXYlooLX53lRCxo175D1uwFLqnpOQKBgACB
ty7BjJ998nXaODWN2ETzb/ZiOCwJDCi2rYzJc0pSbaS5BPtRbY+/ZsFlibs0a2nc
RVoQ+owuKhCbMGl/1lCZ6uExDE/ZVq0ORIDxYpT9zDw0DTB/D8AmAt2SRG2tP5cA
yZJnm0oYfPjG5vNuJHMfPAA/XEVHcj2Z30d2LdRPAoGBAOB1RRJVZ8PQp1v/vW0B
mUS8MRsgkirIVqJJndpaZwOQlM2sxS81r0cbJON0UeXRHR675WtVB0IdimPmSx1l
5KXqX/JR/zOHbtRLS0GtuGgwjtKHFVMSkEefTgC/TvqZFODf89/9lRaeeIe1aYOw
dFy0L7frROOGfCQjkRicwXWo
-----END PRIVATE KEY-----"""
client_email = "streamlit-kost-access@kost-management-466414.iam.gserviceaccount.com"
client_id = "106536013481306394186"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-kost-access%40kost-management-466414.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
